development:
  client_id: development_client_id
  secret: development_secret
test:
  client_id: test_client_id
  secret: test_secret
staging:
  client_id: staging_client_id
  secret: staging_secret
production:
  client_id: production_client_id
  secret: production_secret